version: "2"
services:

  report:
    image: openlmis/dev:10
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - '.:/app'
      - 'gradlecache:/gradle'
    env_file: .env

  db:
    ports:
      - "5432"

volumes:
  gradlecache:
    external: false
